apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/sales/
patches:
- path: ./dev-sales-patch.yaml
images:
- name: service-image
  newName: krumk/service/sales-api
  newTag: 0.0.1
